---
- hosts: all
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install nginx
      apt: name=nginx state=present

    - name: change index.html
      template: 
        src: index.html.j2 
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: 0755